FROM node:18-alpine AS builder
WORKDIR /backend-app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

FROM node:18-alpine AS runtime
WORKDIR /backend-app
ENV NODE_ENV=production

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production
COPY --from=builder /backend-app/dist ./dist
COPY --from=builder /backend-app/src/i18n ./src/i18n

EXPOSE 4200
CMD ["node", "dist/main.js"]
