services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend-app
    depends_on:
      - postgres
    ports:
      - '4200:4200'
    networks:
      - app_network
    env_file:
      - .env
    volumes:
      - .:/backend-app
      - /backend-app/node_modules

  postgres:
    image: postgres:17.1
    ports:
      - '5555:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '7777:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
